[tox]
env_list =
    py310, py311, py312, py313, py314
requires = tox-uv
runner = uv-venv

[testenv]
description = run the tests with uv sync
package = skip
commands_pre =
    uv sync --frozen --active
commands =
    python -m src {tty:--color=yes} {posargs}

